---
title: "Hyojeong's Github blog"
date: 2022-04-07
---

title: Hyojeong's Github blog
author: dgkhj
email: your-email@domain.com
description: > # lalalala

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
